name: Integration tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  happy-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up happy-path test
        run: tests/all-up-test.sh
  validator-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up test with a validator out
        run: tests/all-up-test.sh VALIDATOR_OUT
  valset-stress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up valset stress test
        run: tests/all-up-test.sh VALSET_STRESS
  batch-stress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up batch stress test
        run: tests/all-up-test.sh BATCH_STRESS
